# Generated by Django 2.1.5 on 2019-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_cart', '0002_auto_20190121_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.FloatField(),
        ),
    ]
